### PR TITLE
Fixed build issues

### PR DESCRIPTION
**Pull request by thekalinga**
1. Fixed the gradle build issues
2. Fixed the issue with `org.xmlpull.v1.XmlPullParserFactory` in java 9
3. Added readme

### CODE REVIEW

**Comment by thekalinga** [comment]
Thanks for merging. Can you publish a new release `3.0.0`?

**Comment by stefanhaustein** [comment]
Wouldn't it make sense to call it 2.5.0 -- there is no API change after all?

Am Mo., 14. Sept. 2020 um 06:26 Uhr schrieb Ashok Koyi <
notifications@github.com>:

**Comment by thekalinga** [comment]
From the end user pouint of view, couple of things changed

1. This version does not bomb on java 9 & above (an enhancement)
2. Version of xmlpull in `src/main/resources/META-INF/services/org.xmlpull.v1.XmlPullParserFactory` changed from a format of `1.3.3.1` -> `1.4.0.0` (a bug fix)

Strictly speaking `2.5.0` is most appropropriate enough, but the reason why I proposed `3.0.0` is to ensure that people its easy for people to remember that a major change (aka support for java 9) than when they look at `2.5.0`. I'm okay either ways. I will leave it upto your judgement.

**Comment by thekalinga** [comment]
If you want to keep it at `2.5.0`, please update version within `build.gradle` to `2.5.0` before publishing

**Comment by thekalinga** [comment]
After few of mins of thinking `2.5.0` is the appropriate one as people will know there are no breaking changes from library's point of view. Which makes their lives much simper than moving to `3.0.0`

**Comment by stefanhaustein** [comment]
Ok thanks! So the release tag will be "v2.5.0" for consistency with the others / following github suggestions. Should I include the "v" in build.gradle? Do we need to duplicate the version there at all? I don't seem to have it in any other project?

**Comment by thekalinga** [comment]
Sorry for delay in responding. I dont see any good reason for `v` prefix.

**Comment by thekalinga** [comment]
Can you publish the release in github so that people can refer to it by `2.5.0` instead of commit number?

**Comment by stefanhaustein** [comment]
Doesn't it need to be consistent with the release tag, which has the
leading v as per github recommendations...?

Am Mi., 30. Sept. 2020 um 11:36 Uhr schrieb Ashok Koyi <
notifications@github.com>:

**Comment by stefanhaustein** [comment]
Released as version 2.5.0 with tag v2.5.0

**Pull request merged**
